vault:
  secretPaths:
    mongodb:
      mappings:
        MONGO_URI: "url"
    identity-oidc:
      mappings:
        AM_MCP_CLIENT_SECRET: "AM_MCP_CLIENT_SECRET"
    observability:
      mappings:
        LANGFUSE_PUBLIC_KEY: "LANGFUSE_PUBLIC_KEY"
        LANGFUSE_SECRET_KEY: "LANGFUSE_SECRET_KEY"

    otel:
      mappings:
        TRACING_SAMPLING_PROBABILITY: "TRACING_SAMPLING_PROBABILITY"
