environment: preprod
replicaCount: 1

vault:
  enabled: true
  secretPaths:
    spt-poc:
      path: apps/data/preprod/services/am-spt-poc

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.middlewares: >-
      am-apps-preprod-global-cors@kubernetescrd,
      am-apps-preprod-strip-prefix-apps@kubernetescrd
  hosts:
    - host: am.asrax.in
      paths:
        - path: /spt-poc
          pathType: Prefix

env:
  APP_ENV: preprod
  LOG_LEVEL: INFO
  ROOT_PATH: /spt-poc
  DEFAULT_ENVIRONMENT: preprod
