"""Detailed API flow definitions for auth / users / sessions / subscription."""
from __future__ import annotations

from typing import Any

# Each flow is an ordered list of steps.
# step kinds: call_tool | discover | raw_http
# gates:
#   prod_safe       — always eligible
#   ephemeral_user  — GrowthBook qa-auth-ephemeral-user-flows (throwaway user)

AUTH_USER_API_FLOWS: list[dict[str, Any]] = [
    {
        "id": "FLOW_EPHEMERAL_SETUP",
        "title": "Create throwaway user → login (GrowthBook gated)",
        "gate": "ephemeral_user",
        "uses_ephemeral": True,
        "steps": [
            {
                "id": "register",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/register",
                "method": "post",
                "exact_path": "/auth/register",
                "uses_unique_register_payload": True,
                "capture_ephemeral_creds": True,
            },
            {
                "id": "force_verify",
                "kind": "keycloak_force_verify",
                "note": "Keycloak admin force emailVerified (needs KEYCLOAK_* env)",
            },
            {
                "id": "login",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/login",
                "method": "post",
                "uses_ephemeral_creds": True,
                "capture_tokens": True,
            },
            {
                "id": "resend_verify",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/verify-email/resend",
                "method": "post",
                "exact_path": "/auth/verify-email/resend",
                "uses_ephemeral_email_body": True,
                "optional_service": True,
                "note": "only if force-verify unavailable",
            },
        ],
    },
    {
        "id": "FLOW_LOGIN_SESSION",
        "title": "Login → list sessions → security events → refresh",
        "gate": "prod_safe",
        "steps": [
            {
                "id": "login",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/login",
                "method": "post",
                "uses_spt_auth_creds": True,
                "prefer_ephemeral_creds": True,
                "capture_tokens": True,
            },
            {
                "id": "sessions",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/users/me/login-sessions",
                "method": "get",
                "exact_path": "/users/me/login-sessions",
                "auth": True,
            },
            {
                "id": "security_events",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/users/me/security-events",
                "method": "get",
                "exact_path": "/users/me/security-events",
                "auth": True,
            },
            {
                "id": "users_me",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/users/me",
                "method": "get",
                "exact_path": "/users/me",
                "auth": True,
                "allow_5xx_as_defect": True,
            },
            {
                "id": "refresh",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/refresh",
                "method": "post",
                "uses_refresh_token": True,
            },
        ],
    },
    {
        "id": "FLOW_LOGOUT",
        "title": "Login → logout current token",
        "gate": "prod_safe",
        "steps": [
            {
                "id": "login",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/login",
                "method": "post",
                "uses_spt_auth_creds": True,
                "prefer_ephemeral_creds": True,
                "capture_tokens": True,
            },
            {
                "id": "logout",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/logout",
                "method": "post",
                "auth": True,
                "uses_access_token_body": True,
            },
        ],
    },
    {
        "id": "FLOW_LOGOUT_ALL_DEVICES",
        "title": "Login → DELETE all login-sessions (logout everywhere)",
        "gate": "ephemeral_user",
        "uses_ephemeral": True,
        "steps": [
            {
                "id": "login",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/login",
                "method": "post",
                "uses_ephemeral_creds": True,
                "capture_tokens": True,
            },
            {
                "id": "logout_all",
                "kind": "raw_http",
                "service": "am-identity",
                "path_contains": "/users/me/login-sessions",
                "exact_path": "/users/me/login-sessions",
                "method": "delete",
                "auth": True,
            },
            {
                "id": "relogin",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/login",
                "method": "post",
                "uses_ephemeral_creds": True,
                "capture_tokens": True,
                "note": "re-login after logout-all so later flows still have a session",
            },
        ],
    },
    {
        "id": "FLOW_FORGOT_PASSWORD",
        "title": "Request password reset (no confirm on prod)",
        "gate": "prod_safe",
        "steps": [
            {
                "id": "password_reset",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/password-reset",
                "method": "post",
                "exact_path": "/auth/password-reset",
                "uses_spt_email_only": True,
                "prefer_ephemeral_email": True,
            },
            {
                "id": "password_reset_confirm",
                "kind": "discover",
                "service": "am-identity",
                "path_contains": "/auth/password-reset/confirm",
                "method": "post",
                "note": "confirm requires email token — nonprod manual / mailbox",
            },
        ],
    },
    {
        "id": "FLOW_GOOGLE_OAUTH",
        "title": "Google OAuth URL generation (stop before credentials)",
        "gate": "prod_safe",
        "steps": [
            {
                "id": "google_url",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/google/url",
                "method": "post",
                "payload_from_env": {
                    "redirect_uri": "FLOW_GOOGLE_REDIRECT_URI",
                },
                "payload": {
                    "redirect_uri": "https://am.asrax.in/",
                },
                "allow_4xx_as_expected": True,
                "note": "400 if redirect_uri not allow-listed — set FLOW_GOOGLE_REDIRECT_URI",
            },
            {
                "id": "google_token",
                "kind": "discover",
                "service": "am-identity",
                "path_contains": "/auth/google/token",
                "method": "post",
                "note": "manual_oauth — needs Google auth code",
            },
        ],
    },
    {
        "id": "FLOW_REGISTER_NONPROD",
        "title": "Create user via API (covered by FLOW_EPHEMERAL_SETUP)",
        "gate": "ephemeral_user",
        "uses_ephemeral": True,
        "alias_of": "FLOW_EPHEMERAL_SETUP",
        "steps": [
            {
                "id": "register_alias",
                "kind": "discover",
                "service": "am-identity",
                "path_contains": "/auth/register",
                "method": "post",
                "note": "executed in FLOW_EPHEMERAL_SETUP when GrowthBook flag is on",
            },
        ],
    },
    {
        "id": "FLOW_SUBSCRIPTION",
        "title": "Subscription plans / me / time-left fields",
        "gate": "ephemeral_user",
        "uses_ephemeral": True,
        "steps": [
            {
                "id": "login",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/login",
                "method": "post",
                "uses_ephemeral_creds": True,
                "capture_tokens": True,
            },
            {
                "id": "sub_health",
                "kind": "call_tool",
                "service": "am-subscription",
                "path_contains": "/health",
                "method": "get",
                "optional_service": True,
            },
            {
                "id": "sub_plans",
                "kind": "call_tool",
                "service": "am-subscription",
                "tool_match": ["plan"],
                "method": "get",
                "optional_service": True,
                "auth": True,
            },
            {
                "id": "sub_me",
                "kind": "call_tool",
                "service": "am-subscription",
                "tool_match": ["subscription", "me", "current"],
                "method": "get",
                "optional_service": True,
                "auth": True,
                "note": "Expect trial/expires/time-left fields when OpenAPI is live",
            },
            {
                "id": "sub_ai_proxy",
                "kind": "raw_http",
                "service": "am-identity",
                "base_url_override": "https://am.asrax.in",
                "exact_path": "/ai/subscription/plans",
                "method": "get",
                "auth": True,
                "optional_service": True,
                "note": "gateway AI proxy fallback when subscription OpenAPI is HTML",
            },
        ],
    },
    {
        "id": "FLOW_EPHEMERAL_CLEANUP",
        "title": "Request account deletion for throwaway user",
        "gate": "ephemeral_user",
        "uses_ephemeral": True,
        "steps": [
            {
                "id": "login",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/auth/login",
                "method": "post",
                "uses_ephemeral_creds": True,
                "capture_tokens": True,
            },
            {
                "id": "request_deletion",
                "kind": "call_tool",
                "service": "am-identity",
                "path_contains": "/users/me/request-deletion",
                "method": "post",
                "exact_path": "/users/me/request-deletion",
                "auth": True,
                "payload": {
                    "feedback": "qa-auth-ephemeral-user-flows cleanup",
                },
            },
            {
                "id": "keycloak_disable",
                "kind": "keycloak_disable",
                "note": "fallback cleanup if request-deletion fails",
                "optional_service": True,
            },
        ],
    },
]
