apiVersion: v1
kind: Pod
metadata:
  name: spt-pvc-check
  namespace: load-testing
spec:
  restartPolicy: Never
  containers:
    - name: check
      image: busybox
      command: ["sleep", "120"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: am-spt-poc-data
